### ISSUE TITLE
Typo in about text

### ISSUE THREAD

**Issue by timlindsk** [Sundsvallskommun/.github#9]
**Describe the bug**
The about text contains a typo:
"About

Sundsvalls Kommuns deault files and shared workflows "

Should probably be:

"About

Sundsvalls Kommuns default files and shared workflows"

The change being "deault" -> "default"

**To Reproduce**
-

**Expected behavior**
-

**Logs**
-

**Additional context**
-

**Comment by cheezi0747** [comment]
Fixed
